// AUTO-GENERATED by scripts/build_cases.py
// Do not edit manually.

const CASES_DB = {
  "1": [
    {
      "case_id": "19",
      "image": "cases/case_19/ekg.gif",
      "clinical_history": "The patient is 40-yr-old female admitted with atypical chest pain and a big surprise on the ECG. (Repeat ECG showed same appearance.) The findings are most consistent with which ONE of the following diagnoses?",
      "diagnosis": "Dextrocardia defined as rotation of the heart so that the left atrium (LA) and ventricle are on the right side of the right atrium (RA) and right ventricle (RV). The apex of the heart is therefore formed by the left ventricle (LV) that faces the right axillary line in the right side of the chest. The ECG is notable for 1) inverted P waves in 1 and aVL; 2) negative...",
      "impression": "Dextrocardia",
      "report": {
        "rhythm": "Sinus rhythm (inferred from normal PR and inverted P waves)",
        "rate": "N/A",
        "axis": "Right axis deviation (negative QRS complex in lead I)",
        "intervals": "PR: Normal; QRS: N/A; QTc: N/A",
        "findings": "Inverted P waves in leads I and aVL; negative QRS complex and T wave in lead I; progressively decreasing voltage across the precordium; lead II and lead III morphology reversal",
        "impression": "Dextrocardia"
      },
      "topics": [
        "Uncategorized"
      ],
      "difficulty": 4,
      "options": [
        "Dextrocardia",
        "Acute/evolving inferior ST-elevation myocardial infarction (STEMI) with associated AV Wenckebach block, likely due to dominant right coronary artery occlusion.",
        "a) Mixed mitral stenosis and regurgitation is most likely.",
        "The left anterior descending (LAD)."
      ],
      "correct_idx": 0
    },
    {
      "case_id": "1",
      "image": "cases/case_1/ekg.gif",
      "clinical_history": "21-year-old female with a history of \"seizure\" disorder.  She is on no medications and her electrolytes are normal. This ECG is most consistent with which ONE of the following?",
      "diagnosis": "Dx: Congenital (hereditary) long QT syndrome. The ECG demonstrates sinus rhythm with a very prolonged QT interval of 0.6 second. Note the broad T waves with notching (or possibly U waves) in the precordial leads. This characteristic may identify patients with long QT syndrome at increased risk for torsade de pointes and syncope and sudden death. Patients at high risk of recurrent syncope or sudden death are usually considered for...",
      "impression": "Congenital (hereditary) long QT syndrome",
      "report": {
        "rhythm": "Normal Sinus Rhythm",
        "rate": "52 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QT: 600 ms, QTc: 557 ms",
        "findings": "Markedly prolonged QT interval (0.6 seconds), broad T waves with prominent notching in precordial leads (V2-V4), sinus bradycardia.",
        "impression": "Congenital (hereditary) long QT syndrome"
      },
      "topics": [
        "Long QT Syndrome"
      ],
      "difficulty": 2,
      "options": [
        "What is the patient's age?",
        "Hypokalemia.",
        "Congenital (hereditary) long QT syndrome",
        "a) There are hyperacute T waves and ST elevations localized in the anterior leads."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "2",
      "image": "cases/case_2/ekg.gif",
      "clinical_history": "18-year-old pre-op ECG for knee surgery. What does this ECG show?",
      "diagnosis": "Limb lead reversal. The left and right arm leads are reversed. The clue is inversion of the P wave and QRS complex in lead I. Whenever you see a negative P wave and QRS complex in lead I the likely diagnosis is limb lead reversal. Dextrocardia is another possibility, but in dextrocardia there is loss of R wave progression in the left chest leads which is not seen in this...",
      "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
      "report": {
        "rhythm": "Sinus arrhythmia",
        "rate": "Approx. 75 bpm (variable due to respiratory sinus arrhythmia)",
        "axis": "Apparent Right Axis Deviation (Lead I negative, aVF positive)",
        "intervals": "PR: ~160 ms, QRS: ~80 ms, QTc: ~450 ms",
        "findings": "Inverted P wave, QRS complex, and T wave in lead I; dissimilarity of QRS morphology between leads I and V6; normal R wave progression in precordial leads; slight J-point and ST-segment elevations consistent with benign early repolarization.",
        "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia."
      },
      "topics": [
        "Uncategorized"
      ],
      "difficulty": 2,
      "options": [
        "He is having an inferior myocardial infarction (MI).",
        "Sinus rhythm with atrial bigeminy (this pattern starts after the 4th sinus beat).",
        "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
        "At first glance, this narrow complex tachycardia (NCT) might appear to be \"sinus tachycardia.\"  However, a second look r"
      ],
      "correct_idx": 2
    }
  ],
  "2": [
    {
      "case_id": "19",
      "image": "cases/case_19/ekg.gif",
      "clinical_history": "The patient is 40-yr-old female admitted with atypical chest pain and a big surprise on the ECG. (Repeat ECG showed same appearance.) The findings are most consistent with which ONE of the following diagnoses?",
      "diagnosis": "Dextrocardia defined as rotation of the heart so that the left atrium (LA) and ventricle are on the right side of the right atrium (RA) and right ventricle (RV). The apex of the heart is therefore formed by the left ventricle (LV) that faces the right axillary line in the right side of the chest. The ECG is notable for 1) inverted P waves in 1 and aVL; 2) negative...",
      "impression": "Dextrocardia",
      "report": {
        "rhythm": "Sinus rhythm (inferred from normal PR and inverted P waves)",
        "rate": "N/A",
        "axis": "Right axis deviation (negative QRS complex in lead I)",
        "intervals": "PR: Normal; QRS: N/A; QTc: N/A",
        "findings": "Inverted P waves in leads I and aVL; negative QRS complex and T wave in lead I; progressively decreasing voltage across the precordium; lead II and lead III morphology reversal",
        "impression": "Dextrocardia"
      },
      "topics": [
        "Uncategorized"
      ],
      "difficulty": 4,
      "options": [
        "The rhythm is sinus with underlying left anterior fascicular block (LAFB), and 2:1 conduction in the left posterior fasc",
        "e)  Three or more consecutive ectopic (non-sinus) P waves are present at a rapid rate.",
        "Sinus rhythm is present (P wave rate 94/min) with AV Wenckebach (3:2 and 4:3 AV ) conduction.",
        "Dextrocardia"
      ],
      "correct_idx": 3
    },
    {
      "case_id": "1",
      "image": "cases/case_1/ekg.gif",
      "clinical_history": "21-year-old female with a history of \"seizure\" disorder.  She is on no medications and her electrolytes are normal. This ECG is most consistent with which ONE of the following?",
      "diagnosis": "Dx: Congenital (hereditary) long QT syndrome. The ECG demonstrates sinus rhythm with a very prolonged QT interval of 0.6 second. Note the broad T waves with notching (or possibly U waves) in the precordial leads. This characteristic may identify patients with long QT syndrome at increased risk for torsade de pointes and syncope and sudden death. Patients at high risk of recurrent syncope or sudden death are usually considered for...",
      "impression": "Congenital (hereditary) long QT syndrome",
      "report": {
        "rhythm": "Normal Sinus Rhythm",
        "rate": "52 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QT: 600 ms, QTc: 557 ms",
        "findings": "Markedly prolonged QT interval (0.6 seconds), broad T waves with prominent notching in precordial leads (V2-V4), sinus bradycardia.",
        "impression": "Congenital (hereditary) long QT syndrome"
      },
      "topics": [
        "Long QT Syndrome"
      ],
      "difficulty": 2,
      "options": [
        "At first glance, this narrow complex tachycardia (NCT) might appear to be \"sinus tachycardia.\"  However, a second look r",
        "The findings are that of a reentrant type PSVT.",
        "Congenital (hereditary) long QT syndrome",
        "Diffuse anterior T wave inversions suggestive of probable ischemia or non-Q wave myocardial infarction (Wellens' syndrome), most likely due to transient proximal LAD occlusion/spasm with subsequent myocardial stunning."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "2",
      "image": "cases/case_2/ekg.gif",
      "clinical_history": "18-year-old pre-op ECG for knee surgery. What does this ECG show?",
      "diagnosis": "Limb lead reversal. The left and right arm leads are reversed. The clue is inversion of the P wave and QRS complex in lead I. Whenever you see a negative P wave and QRS complex in lead I the likely diagnosis is limb lead reversal. Dextrocardia is another possibility, but in dextrocardia there is loss of R wave progression in the left chest leads which is not seen in this...",
      "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
      "report": {
        "rhythm": "Sinus arrhythmia",
        "rate": "Approx. 75 bpm (variable due to respiratory sinus arrhythmia)",
        "axis": "Apparent Right Axis Deviation (Lead I negative, aVF positive)",
        "intervals": "PR: ~160 ms, QRS: ~80 ms, QTc: ~450 ms",
        "findings": "Inverted P wave, QRS complex, and T wave in lead I; dissimilarity of QRS morphology between leads I and V6; normal R wave progression in precordial leads; slight J-point and ST-segment elevations consistent with benign early repolarization.",
        "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia."
      },
      "topics": [
        "Uncategorized"
      ],
      "difficulty": 2,
      "options": [
        "c)  There are diffuse ST elevations (I, II, aVL, aVF, V2-V6) with associated PR segment deviations (elevated PR in aVR; ",
        "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
        "Coarse atrial fibrillation (not flutter) is present with a slow ventricular response.",
        "The rhythm is sinus with underlying left anterior fascicular block (LAFB), and 2:1 conduction in the left posterior fasc"
      ],
      "correct_idx": 1
    }
  ],
  "3": [
    {
      "case_id": "50",
      "image": "cases/case_50/ekg.gif",
      "clinical_history": "85-year-old patient with valvular heart disease and congestive heart failure. Houseofficer called this normal sinus rhythm. What do you think?",
      "diagnosis": "It's only NSR if that stands for \"Not Sinus Rhythm.\" Note that there are two P's for every QRS (see V1) and that the atrial activity at 176/min is negative in lead 2. This is atrial (NOT sinus) tachycardia with 2:1 block (conduction). Block is almost certainly at the AV node level (\"type 1\" mechanism). Always exclude digitalis excess with this arrhythmia (not present here). The ECG also shows low...",
      "impression": "Atrial tachycardia with 2:1 conduction block and the 'ECG-CHF triad' (low limb lead voltage, LVH, and poor R-wave progression), indicative of advanced congestive heart failure.",
      "report": {
        "rhythm": "Atrial tachycardia with 2:1 block",
        "rate": "Atrial rate 176 bpm, Ventricular rate 88 bpm",
        "axis": "Left axis deviation",
        "intervals": "QRS ~90 ms, QTc ~410 ms",
        "findings": "Low limb lead voltage (<5mm in all limb leads), left ventricular hypertrophy (LVH) by precordial voltage criteria, slow R-wave progression (V1-V4), negative P-waves in inferior leads (Lead II), and ST-T segment abnormalities consistent with LVH or ischemia",
        "impression": "Atrial tachycardia with 2:1 conduction block and the 'ECG-CHF triad' (low limb lead voltage, LVH, and poor R-wave progression), indicative of advanced congestive heart failure."
      },
      "topics": [
        "Myocardial Infarction",
        "Left Ventricular Hypertrophy",
        "Normal Sinus Rhythm"
      ],
      "difficulty": 3,
      "options": [
        "Atrial tachycardia with 2:1 conduction block and the 'ECG-CHF triad' (low limb lead voltage, LVH, and poor R-wave progression), indicative of advanced congestive heart failure.",
        "Acute cor pulmonale secondary to pulmonary embolism (PE).",
        "He is having an evolving anteroseptal myocardial infarction attributable to cocaine use.",
        "The ECG shows sinus rhythm with complete right bundle branch block (RBBB) with left anterior fascicular block (LAFB)."
      ],
      "correct_idx": 0
    },
    {
      "case_id": "76",
      "image": "cases/case_76/ekg.gif",
      "clinical_history": "48-yr-old male: what service is patient on?",
      "diagnosis": "Neurology/Neurosurgery. The patient has Parkinson's disease, with normal sinus rhythm. The clue is the tremor artifact, best seen in the limb leads. This artifact may sometimes be confused for atrial fibrillation/flutter, and when of very high magnitude may even look like torsades de pointes!",
      "impression": "Neurology/Neurosurgery.",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "Neurology/Neurosurgery."
      },
      "topics": [
        "Atrial Fibrillation",
        "Normal Sinus Rhythm"
      ],
      "difficulty": 2,
      "options": [
        "c)  Findings here are highly suggestive of moderately severe Chronic obstructive pulmonary disease (COPD), including 1) ",
        "a) There are hyperacute T waves and ST elevations localized in the anterior leads.",
        "Neurology/Neurosurgery.",
        "d)  ECG shows a constellation of findings consistent with acute cor pulmonale from massive pulmonary embolus (PE) includ"
      ],
      "correct_idx": 2
    },
    {
      "case_id": "119",
      "image": "cases/case_119/ekg.gif",
      "clinical_history": "What is the rhythm?",
      "diagnosis": "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs).  Note that simultaneous lead II (bottom) does not show this, and normal rhythm is not affected by the spurious \"beats.\"",
      "impression": "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs).",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs)."
      },
      "topics": [
        "Premature Ventricular Contractions",
        "Normal Sinus Rhythm"
      ],
      "difficulty": 3,
      "options": [
        "c)  There is a wide complex tachycardia at about 165/min with an right bundle branch block (RBBB) morphology.",
        "The findings are that of a reentrant type PSVT.",
        "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs).",
        "He is having an evolving anteroseptal myocardial infarction attributable to cocaine use."
      ],
      "correct_idx": 2
    }
  ],
  "4": [
    {
      "case_id": "21",
      "image": "cases/case_21/ekg.gif",
      "clinical_history": "The patient is a 47-yr-old, asymptomatic  woman with the following ECG finding, reportedly persent since birth.",
      "diagnosis": "The tracing shows sinus rhythm with complete heart (AV) block and an A-V junctional (narrow QRS) type escape rhythm. Note that the P-P intervals \"surrounding\" individual QRS complexes are shorter than the P-P intervals between two QRS complexes. Sinus rate variation of this type with complete heart block is called ventriculophasic sinus arrhythmia. The patient had congenital complete heart block. This entity is usually idiopathic but may be secondary to...",
      "impression": "Congenital complete heart block with a stable A-V junctional escape rhythm; asymptomatic and no pacemaker required at this time.",
      "report": {
        "rhythm": "Sinus rhythm with complete heart (AV) block and A-V junctional escape rhythm",
        "rate": "N/A",
        "axis": "N/A",
        "intervals": "Narrow QRS; PR interval is dissociated (complete heart block)",
        "findings": "Complete heart block, ventriculophasic sinus arrhythmia, proximal junctional escape rhythm",
        "impression": "Congenital complete heart block with a stable A-V junctional escape rhythm; asymptomatic and no pacemaker required at this time."
      },
      "topics": [
        "Premature Atrial Contractions"
      ],
      "difficulty": 3,
      "options": [
        "a) Electrophysiology study revealed both slow AV nodal conduction (note long PR of conducted beats) and infra-nodal bloc",
        "Marked junctional bradycardia (about 25 beats/min).",
        "Borderline sinus tachycardia is present with a markedly prolonged PR at about 300 ms (\"1st degree AV block\").",
        "Congenital complete heart block with a stable A-V junctional escape rhythm; asymptomatic and no pacemaker required at this time."
      ],
      "correct_idx": 3
    },
    {
      "case_id": "6",
      "image": "cases/case_6/ekg.gif",
      "clinical_history": "71-year-old female with mitral stenosis and a history of atrial fibrillation.  What is the rhythm now?",
      "diagnosis": "Rhythm: Ectopic atrial (non-sinus) rhythm (borderline for atrial tachycardia -- atrial rate around 95/min) with 2:1 block and 3:2 AV Wenckebach (beats 4 and 5), accounting for the bradycardic QRS rate (about 48/min). Note the negative P waves in lead II indicating a non-sinus pacemaker. Other important abnormalities: right bundle branch block, left anterior fascicular block and a markedly prolonged QT(U) interval. This patient was on digoxin and quinidine. The...",
      "impression": "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity.",
      "report": {
        "rhythm": "Ectopic atrial rhythm (borderline atrial tachycardia) with mixed 2:1 AV block and 3:2 AV Wenckebach",
        "rate": "Atrial rate: ~95 bpm; Ventricular rate: ~48 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: variable (due to Wenckebach); QRS: >120 ms (widened); QT(U): markedly prolonged",
        "findings": "Negative P waves in inferior leads (indicating ectopic atrial focus), Right Bundle Branch Block (RBBB), Left Anterior Fascicular Block (LAFB), markedly prolonged QT(U) interval most prominent in V2-V5",
        "impression": "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity."
      },
      "topics": [
        "Atrial Fibrillation",
        "Long QT Syndrome",
        "Right Bundle Branch Block",
        "AV Block",
        "Premature Atrial Contractions"
      ],
      "difficulty": 4,
      "options": [
        "This is a classic inferior/posterior/right ventricular myocardial infarction (MI) pattern.",
        "The patient had hypertrophic obstructive cardiomyopathy with chronic left bundle branch block (LBBB).",
        "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity.",
        "Atrial fibrillation with a moderate ventricular response plus a single ventricular pacemaker escape spike (fifth beat, w"
      ],
      "correct_idx": 2
    },
    {
      "case_id": "27",
      "image": "cases/case_27/ekg.gif",
      "clinical_history": "A 52-year-old man.  What is his chief complaint? What is the rhythm disturbance? Look carefully at both ends of strip.",
      "diagnosis": "Acute infero-lateral and probably posterior myocardial infarction (MI) with inferior Q waves and hyperacute ST-T complexes inferiorly and laterally with reciprocal ST depressions V1-V3. Tall initial R waves in V1-V3 with right bundle branch block. There is second degree AV block (Type 1) with 2:1 block initially and then 3:2 AV Wenckebach with underlying sinus rate of about 85/min. Left axis deviation is present. However, since this is an inferior...",
      "impression": "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1).",
      "report": {
        "rhythm": "Sinus rhythm with second-degree AV block (Type 1), featuring initial 2:1 block followed by 3:2 Wenckebach conduction.",
        "rate": "Sinus rate ~85 bpm; Ventricular rate approximately 40-50 bpm.",
        "axis": "Left axis deviation.",
        "intervals": "PR: Variable (prolonging until a dropped beat); QRS: >120 ms (widened, consistent with RBBB); QTc: Not specifically calculated but appears prolonged due to hyperacute T-wave changes.",
        "findings": "Hyperacute ST-segment elevation and T-waves in leads II, III, aVF, and V4-V6; pathologic Q waves in inferior leads (II, III, aVF); reciprocal ST-segment depression in V1-V3; tall initial R waves in V1-V3; Right Bundle Branch Block (RBBB) morphology.",
        "impression": "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1)."
      },
      "topics": [
        "Myocardial Infarction",
        "Right Bundle Branch Block",
        "AV Block",
        "Premature Atrial Contractions"
      ],
      "difficulty": 2,
      "options": [
        "Atrial fibrillation with a moderate ventricular response plus a single ventricular pacemaker escape spike (fifth beat, w",
        "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1).",
        "From the surface ECG, the rhythm is likely either slow, reentrant atrial flutter in context of cardiomyopathy with an en",
        "He is having an inferior myocardial infarction (MI)."
      ],
      "correct_idx": 1
    }
  ],
  "5": [
    {
      "case_id": "46",
      "image": "cases/case_46/ekg.gif",
      "clinical_history": "What is the rhythm?",
      "diagnosis": "Atrial flutter. Don't miss hidden atrial (F) wave just after QRS. This is atrial flutter with 2:1 conduction. Note that with atrial flutter there aren't P waves per se but atrial waves. So if you talk about atrial flutter do not say \"the P waves....\" since once you say P wave, the informed listener will probably assume it's not atrial fibrillation or atrial flutter. On the other hand, depending on...",
      "impression": "Atrial flutter with 2:1 conduction (ventricular rate 150 bpm), left axis deviation, and left ventricular hypertrophy with secondary repolarization changes.",
      "report": {
        "rhythm": "Atrial flutter with 2:1 conduction",
        "rate": "Ventricular rate: ~150 bpm; Atrial rate: ~300 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: N/A (Atrial flutter); QRS: ~90 ms; QTc: ~470 ms",
        "findings": "Typical sawtooth atrial flutter waves (negative polarity in leads II, III, aVF); 2:1 AV conduction with hidden F-waves following the QRS complexes; Left ventricular hypertrophy (LVH) by voltage (SV2 + RV5 > 35mm) with associated ST-T wave abnormalities (strain pattern) in lateral leads; Possible prior inferior wall myocardial infarction based on Q-waves/rS complexes in inferior leads.",
        "impression": "Atrial flutter with 2:1 conduction (ventricular rate 150 bpm), left axis deviation, and left ventricular hypertrophy with secondary repolarization changes."
      },
      "topics": [
        "Myocardial Infarction",
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Left Ventricular Hypertrophy"
      ],
      "difficulty": 3,
      "options": [
        "c) The patient had documented Lyme carditis.",
        "The ECG is within normal limits.",
        "c)  There are diffuse ST elevations (I, II, aVL, aVF, V2-V6) with associated PR segment deviations (elevated PR in aVR; ",
        "Atrial flutter with 2:1 conduction (ventricular rate 150 bpm), left axis deviation, and left ventricular hypertrophy with secondary repolarization changes."
      ],
      "correct_idx": 3
    },
    {
      "case_id": "228",
      "image": "cases/case_228/ekg.gif",
      "clinical_history": "What is this arrhythmia?",
      "diagnosis": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min). The baseline shows the characteristic wriggly fibrillatory activity (not discrete P waves) and the ventricular response is highly irregular (irregularly irregular). The absence of clearly defined P waves excludes sinus rhythm with premature atrial complexes (PACs) or multifocal atrial tachycardia (MAT.) There are also no consistent flutter (saw-tooth) waves and this...",
      "impression": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min).",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min)."
      },
      "topics": [
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Ventricular Tachycardia",
        "Supraventricular Tachycardia",
        "Premature Atrial Contractions"
      ],
      "difficulty": 2,
      "options": [
        "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min).",
        "a) The rhythm here is actually sinus at a rate of 94/min with 2:1 AV block and very (!) subtle non-conducted P waves hid",
        "d) Patient had documented prior inferior-posterior myocardial infarction (MI).",
        "c) This tracing is most consistent with AIVR originating from the left ventricle and, therefore, accounts for the atypic"
      ],
      "correct_idx": 0
    },
    {
      "case_id": "247",
      "image": "cases/case_247/ekg.gif",
      "clinical_history": "51 year male seen in the emergency department. What is the diagnosis?",
      "diagnosis": "This is a classic ECG obtained during a ventricular fibrillation (VF) cardiac arrest. The findings are typical of ventricular fibrillation with more organized ventricular electrical activity in the second half of the strip consistent with ventricular flutter. There is no evidence of any atrial activity ruling out atrial fibrillation with Wolff-Parkinson-White (WPW )( see Case # 15 ) or atrial flutter with a bundle branch block. The characteristic, systematic variation...",
      "impression": "This is a classic ECG obtained during a ventricular fibrillation (VF) cardiac arrest.",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "This is a classic ECG obtained during a ventricular fibrillation (VF) cardiac arrest."
      },
      "topics": [
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Ventricular Fibrillation",
        "Wolff-Parkinson-White"
      ],
      "difficulty": 2,
      "options": [
        "c) The patient had documented Lyme carditis.",
        "This is a classic ECG obtained during a ventricular fibrillation (VF) cardiac arrest.",
        "e)  Three or more consecutive ectopic (non-sinus) P waves are present at a rapid rate.",
        "e) The ECG shows classic signs of very marked right ventricular hypertrophy (RVH), usually associated with a severe pres"
      ],
      "correct_idx": 1
    }
  ],
  "6": [
    {
      "case_id": "35",
      "image": "cases/case_35/ekg.gif",
      "clinical_history": "Tachycardia and a touch of cyanosis (rhythm and blues). What is major finding in this patient with congestive heart failure (CHF)?",
      "diagnosis": "The major finding is narrow complex tachycardia with atrial rate of about 300 indicating atrial flutter with a slightly variable ventricular response (2:1 conduction, some 3:1 and probably some AV Wenckebach). Atrial flutter is sometimes mistaken (by housestaff at institutions other than your own) for sinus tachycardia. Look, for instance, at V1 where the flutter waves are hard to see vs. lead II where they are more apparent. If only...",
      "impression": "Atrial flutter with variable ventricular response",
      "report": {
        "rhythm": "Atrial flutter",
        "rate": "Atrial rate ~300 bpm, Ventricular rate ~150 bpm",
        "axis": "Normal axis",
        "intervals": "PR: N/A; QRS: 80 ms; QTc: 440 ms",
        "findings": "Narrow complex tachycardia; sawtooth flutter waves best seen in inferior leads (II, III, aVF); variable AV conduction (predominantly 2:1 with some 3:1 and probable Wenckebach)",
        "impression": "Atrial flutter with variable ventricular response"
      },
      "topics": [
        "Atrial Flutter",
        "AV Block"
      ],
      "difficulty": 3,
      "options": [
        "Acute cor pulmonale secondary to pulmonary embolism (PE).",
        "Atrial flutter with variable ventricular response",
        "Congenital (hereditary) long QT syndrome",
        "Atrial fibrillation with a moderate ventricular response plus a single ventricular pacemaker escape spike (fifth beat, w"
      ],
      "correct_idx": 1
    },
    {
      "case_id": "6",
      "image": "cases/case_6/ekg.gif",
      "clinical_history": "71-year-old female with mitral stenosis and a history of atrial fibrillation.  What is the rhythm now?",
      "diagnosis": "Rhythm: Ectopic atrial (non-sinus) rhythm (borderline for atrial tachycardia -- atrial rate around 95/min) with 2:1 block and 3:2 AV Wenckebach (beats 4 and 5), accounting for the bradycardic QRS rate (about 48/min). Note the negative P waves in lead II indicating a non-sinus pacemaker. Other important abnormalities: right bundle branch block, left anterior fascicular block and a markedly prolonged QT(U) interval. This patient was on digoxin and quinidine. The...",
      "impression": "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity.",
      "report": {
        "rhythm": "Ectopic atrial rhythm (borderline atrial tachycardia) with mixed 2:1 AV block and 3:2 AV Wenckebach",
        "rate": "Atrial rate: ~95 bpm; Ventricular rate: ~48 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: variable (due to Wenckebach); QRS: >120 ms (widened); QT(U): markedly prolonged",
        "findings": "Negative P waves in inferior leads (indicating ectopic atrial focus), Right Bundle Branch Block (RBBB), Left Anterior Fascicular Block (LAFB), markedly prolonged QT(U) interval most prominent in V2-V5",
        "impression": "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity."
      },
      "topics": [
        "Atrial Fibrillation",
        "Long QT Syndrome",
        "Right Bundle Branch Block",
        "AV Block",
        "Premature Atrial Contractions"
      ],
      "difficulty": 4,
      "options": [
        "Ischemic heart disease, s/p prior myocardial infarctions MI(s), with very severe left ventricular (LV) dysfunction with ",
        "In addition to prominent sinus tachycardia, there is an intraventricular conduction delay (IVCD) with a rightward or ind",
        "Slow atrial tachycardia with high-grade AV block and bifascicular block; clinical features and EKG findings (prolonged QT/U and AV block) are highly suggestive of digitalis and quinidine toxicity.",
        "Sinus rhythm with atrial bigeminy (this pattern starts after the 4th sinus beat)."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "9",
      "image": "cases/case_9/ekg.gif",
      "clinical_history": "This is the admitting ECG of a previously healthy 49-year-old man who presented with progressive muscle weakness and constipation. He had no chest pain or dyspnea. The ECG is most consistent with which ONE of the following diagnoses?",
      "diagnosis": "The ECG shows sinus rhythm with the following key abnormality: a very short ST segment with a consequently short QT interval (about 300 msec here). The differential diagnosis of a short QT (lower limits are not well-defined) is much narrower than that of prolonged QT. The two chief causes of a short QT are hypercalcemia and digoxin therapy (associated with characteristic \"scooping\" of the ST-T complex). A third and relatively...",
      "impression": "Short QT interval secondary to severe hypercalcemia (16 mg/dL) from parathyroid carcinoma.",
      "report": {
        "rhythm": "Normal Sinus Rhythm",
        "rate": "77 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QT: 300 ms, QTc: 341 ms",
        "findings": "Markedly short ST segment resulting in a short QT interval; the T wave appears to begin almost immediately after the QRS complex.",
        "impression": "Short QT interval secondary to severe hypercalcemia (16 mg/dL) from parathyroid carcinoma."
      },
      "topics": [
        "Ventricular Tachycardia",
        "AV Block"
      ],
      "difficulty": 4,
      "options": [
        "Short QT interval secondary to severe hypercalcemia (16 mg/dL) from parathyroid carcinoma.",
        "c) The K+ was 10.5 mEq/L in a patient with renal  failure.",
        "c) Transposition of the great arteries (TGA).",
        "Sinus rhythm is present with very frequent premature atrial complexes (PACs), creating a trigeminal pattern."
      ],
      "correct_idx": 0
    }
  ],
  "7": [
    {
      "case_id": "255",
      "image": "cases/case_255/ekg.gif",
      "clinical_history": "ECG diagnosis is sinus rhythm with what conduction abnormality?",
      "diagnosis": "The ECG shows sinus rhythm with a complete left bundle branch block (LBBB) pattern (QRS duration 0.16 second) with secondary ST-T wave changes. Bundle branch blocks usually produce \"secondary\" T wave changes such that the ST-T wave vector points opposite in direction of the major vector of the QRS. These secondary ST-T changes are due to the altered sequence of ventricular activation. In a typical right bundle branch block (RBBB),...",
      "impression": "The ECG shows sinus rhythm with a complete left bundle branch block (LBBB) pattern (QRS duration 0.16 second) with secon",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "The ECG shows sinus rhythm with a complete left bundle branch block (LBBB) pattern (QRS duration 0.16 second) with secon"
      },
      "topics": [
        "Myocardial Infarction",
        "Left Bundle Branch Block",
        "Right Bundle Branch Block",
        "Wolff-Parkinson-White"
      ],
      "difficulty": 1,
      "options": [
        "This is a classic inferior/posterior/right ventricular myocardial infarction (MI) pattern.",
        "Sinus bradycardia and Left Bundle Branch Block (LBBB) with primary ST-T wave changes in the inferior leads, diagnostic of an evolving inferior myocardial infarction (confirmed by positive cardiac biomarkers).",
        "The patient had hypertrophic obstructive cardiomyopathy with chronic left bundle branch block (LBBB).",
        "The ECG shows sinus rhythm with a complete left bundle branch block (LBBB) pattern (QRS duration 0.16 second) with secon"
      ],
      "correct_idx": 3
    },
    {
      "case_id": "13",
      "image": "cases/case_13/ekg.gif",
      "clinical_history": "A middle-aged woman with a history of a \"heart murmur\" since childhood presents with worsening dyspnea. The ECG is most consistent with which ONE of the following major diagnoses?",
      "diagnosis": "The ECG reveals sinus rhythm with the following abnormalities: left atrial abnormality (LAA) in concert with a relatively tall R wave (increased Rs ratio) in lead V1 and an inverted T wave in that lead, along with right axis deviation (RAD). The combination of a predominant R wave (even with overall low amplitude QRS voltage) and rightward axis deviation with a normal QRS duration suggests right ventricular hypertrophy. This pattern...",
      "impression": "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy.",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "79 bpm",
        "axis": "Right axis deviation",
        "intervals": "PR: 180 ms, QRS: 80 ms, QTc: 460 ms",
        "findings": "Left atrial abnormality (LAA) with broad P waves (>120 ms) and biphasic P in V1; Right ventricular hypertrophy (RVH) suggested by prominent R wave in V1 (increased R/S ratio), right axis deviation, and inverted T wave in V1; Relatively low amplitude QRS voltage; S1Q3T3 pattern (rS in lead I, qR and T-wave inversion in lead III).",
        "impression": "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy."
      },
      "topics": [
        "Myocardial Infarction",
        "Right Bundle Branch Block",
        "Wolff-Parkinson-White",
        "Right Ventricular Hypertrophy"
      ],
      "difficulty": 3,
      "options": [
        "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy.",
        "Atrial fibrillation (with a moderate ventricular response) and frequent premature ventricular complexes (PVCs).",
        "Sinus bradycardia and Left Bundle Branch Block (LBBB) with primary ST-T wave changes in the inferior leads, diagnostic of an evolving inferior myocardial infarction (confirmed by positive cardiac biomarkers).",
        "He is having an inferior myocardial infarction (MI)."
      ],
      "correct_idx": 0
    },
    {
      "case_id": "33",
      "image": "cases/case_33/ekg.gif",
      "clinical_history": "64-year-old man with increasing pedal edema. What is the ECG diagnosis?",
      "diagnosis": "Sinus rhythm with left atrial abnormality. Most striking are tall right precordial R waves with pathologic inferior and lateral Q waves giving a \"reverse\" type R wave progression. There are also ST-T abnormalities in I, aVL, V6. Thus the patient has coronary artery disease (CAD), s/p large infero-(postero)-lateral myocardial infarction (MI) accounting for congestive heart failure (CHF) findings. Recall that differential diagnosis of tall right precordial R waves includes: 1)...",
      "impression": "Large old infero-postero-lateral myocardial infarction, likely contributing to the patient's clinical signs of congestive heart failure.",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "75 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: 160ms, QRS: 80ms, QTc: ~450ms",
        "findings": "Left atrial abnormality; pathologic Q waves in inferior (II, III, aVF) and lateral (I, aVL, V6) leads; tall R waves in right precordial leads (V1, V2) indicating posterior involvement; 'reverse' R-wave progression; ST-T wave abnormalities in leads I, aVL, and V6.",
        "impression": "Large old infero-postero-lateral myocardial infarction, likely contributing to the patient's clinical signs of congestive heart failure."
      },
      "topics": [
        "Myocardial Infarction",
        "Right Bundle Branch Block",
        "Wolff-Parkinson-White",
        "Right Ventricular Hypertrophy"
      ],
      "difficulty": 3,
      "options": [
        "In addition to prominent sinus tachycardia, there is an intraventricular conduction delay (IVCD) with a rightward or ind",
        "Large old infero-postero-lateral myocardial infarction, likely contributing to the patient's clinical signs of congestive heart failure.",
        "c)  There is a wide complex tachycardia at about 165/min with an right bundle branch block (RBBB) morphology.",
        "From the surface ECG, the rhythm is likely either slow, reentrant atrial flutter in context of cardiomyopathy with an en"
      ],
      "correct_idx": 1
    }
  ],
  "8": [
    {
      "case_id": "3",
      "image": "cases/case_3/ekg.gif",
      "clinical_history": "History: 36-year-old male with hypertension and hypercholesterolemia presents to the emergency room with 3 hrs of chest pain and the following ECG. How would you manage this patient based on this ECG?",
      "diagnosis": "This patient's ECG is consistent with acute pericarditis. Always consider myocardial infarction first when you see ST elevations, but don't forget the differential diagnosis of ST elevations not only includes 1) ischemic heart disease (MI, Prinzmetal angina, ventricular aneurysm) but also 2) pericarditis, 3) left bundle branch block (LBBB) (in V1-V3) and 4) normal (\"early repolarization\") variant (J point elevation). In this ECG two features point to pericarditis: First, the...",
      "impression": "Acute pericarditis",
      "report": {
        "rhythm": "Sinus tachycardia",
        "rate": "110 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 140 ms, QRS: 80 ms, QTc: 430 ms",
        "findings": "Diffuse concave-upward ST-segment elevations in leads I, II, III, aVF, and V2-V6; PR-segment depression in leads II, III, aVF, and V2-V6; PR-segment elevation in lead aVR; Sinus tachycardia.",
        "impression": "Acute pericarditis"
      },
      "topics": [
        "Myocardial Infarction",
        "Pericarditis",
        "Left Bundle Branch Block"
      ],
      "difficulty": 3,
      "options": [
        "This is a classic inferior/posterior/right ventricular myocardial infarction (MI) pattern.",
        "The patient had hypertrophic obstructive cardiomyopathy with chronic left bundle branch block (LBBB).",
        "Acute pericarditis",
        "Atrial fibrillation with a moderate ventricular response plus a single ventricular pacemaker escape spike (fifth beat, w"
      ],
      "correct_idx": 2
    },
    {
      "case_id": "36",
      "image": "cases/case_36/ekg.gif",
      "clinical_history": "A 65-year-old man presents for evaluation of weakness. What should you do before calling the interventional cardiology team for what was called a \"hyperacute myocardial infarction\" pattern?",
      "diagnosis": "Put the \"lytes\" on! This is classic hyperkalemia with tall peaked T waves, along with PR prolongation and probable underlying left ventricular hypertrophy (LVH). The patient has renal disease with hypertension. Note the QRS prolongation also seen with moderate-severe hyperkalemia. The serum potassium level was 9.6mEq/L. Important note:not all tall positive T waves are \"hyperacute.\" The latter term should be reserved for increased T wave positivity secondary to transmural ischemia....",
      "impression": "Severe hyperkalemia (Serum K+ 9.6 mEq/L) and suspected uremic pericarditis.",
      "report": {
        "rhythm": "Sinus rhythm with first-degree AV block",
        "rate": "94 bpm",
        "axis": "Vertical axis (+80 degrees)",
        "intervals": "PR: 240 ms, QRS: 160 ms, QTc: 500 ms",
        "findings": "Tall peaked (tented) T waves, PR and QRS prolongation, left ventricular hypertrophy (LVH) by voltage (deep S waves in V2), broad P waves (left atrial abnormality), PR segment depression in inferior-lateral leads with PR segment elevation in lead aVR.",
        "impression": "Severe hyperkalemia (Serum K+ 9.6 mEq/L) and suspected uremic pericarditis."
      },
      "topics": [
        "Myocardial Infarction",
        "Pericarditis",
        "Hyperkalemia",
        "Left Ventricular Hypertrophy"
      ],
      "difficulty": 3,
      "options": [
        "d)  Note the longer PR in the atrial premature complexes.",
        "Marked junctional bradycardia (about 25 beats/min).",
        "Severe hyperkalemia (Serum K+ 9.6 mEq/L) and suspected uremic pericarditis.",
        "b)  Note loss of R waves V1 - V4, with ST elevations in  V2 - V5/V6 (as well as slightly in I and aVL) with underlying s"
      ],
      "correct_idx": 2
    },
    {
      "case_id": "11",
      "image": "cases/case_11/ekg.gif",
      "clinical_history": "51-year-old male with bicuspid aortic valve, aortic insufficiency and hypertension had an episode of chest pain 2 days prior to this tracing. In this context, this type of pattern of prominent T wave inversions is most likely attributable to which ONE of the following?",
      "diagnosis": "This ECG shows sinus rhythm at about 65 beats/min with diffuse, very prominent anterior T wave inversions consistent with probable ischemia/non-Q wave myocardial infarction (MI). Sometimes this pattern is referred to as Wellens' T waves (de Zwaan C, Bar FW, Janssen JH, et al. Angiographic and clinical characteristics of patients with unstable angina showing an ECG pattern indicating critical narrowing of the proximal LAD coronary artery. Am Heart J. 1989;117:657-...",
      "impression": "Diffuse anterior T wave inversions suggestive of probable ischemia or non-Q wave myocardial infarction (Wellens' syndrome), most likely due to transient proximal LAD occlusion/spasm with subsequent myocardial stunning.",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "65 bpm",
        "axis": "Borderline left axis deviation",
        "intervals": "PR: 220 ms, QRS: ~100 ms, QT/QTc: 480 ms",
        "findings": "Diffuse, very prominent symmetric anterior T wave inversions (V2-V6, I, aVL) consistent with Wellens' pattern; Left atrial abnormality; Left ventricular hypertrophy (LVH) by voltage; Mild PR prolongation; QT prolongation.",
        "impression": "Diffuse anterior T wave inversions suggestive of probable ischemia or non-Q wave myocardial infarction (Wellens' syndrome), most likely due to transient proximal LAD occlusion/spasm with subsequent myocardial stunning."
      },
      "topics": [
        "Myocardial Infarction",
        "Pericarditis",
        "Left Bundle Branch Block",
        "Premature Atrial Contractions",
        "Left Ventricular Hypertrophy"
      ],
      "difficulty": 4,
      "options": [
        "Acute inferior/posterior/lateral myocardial infarction (MI) in a man with situs inversus-type dextrocardia.",
        "Diffuse anterior T wave inversions suggestive of probable ischemia or non-Q wave myocardial infarction (Wellens' syndrome), most likely due to transient proximal LAD occlusion/spasm with subsequent myocardial stunning.",
        "Left pneumothorax causing low lateral precordial lead voltage.",
        "Acute cor pulmonale secondary to pulmonary embolism (PE)."
      ],
      "correct_idx": 1
    }
  ],
  "9": [
    {
      "case_id": "44",
      "image": "cases/case_44/ekg.gif",
      "clinical_history": "30-yr-old man, not on any medication. What waveform is prominent? What is the likely diagnosis, assuming prior normal ECG?",
      "diagnosis": "There are very (!) prominent U waves with Q-T or QT(U) prolongation. He had severe hypokalemia (1.5 mEq/L) due to diarrhea. Calcium was normal, as was magnesium (remember pure hypocalcemia prolongs the ST segment primarily but does not give large U waves.) Obviously, this acquired-type long-QT(U) syndrome puts the subject at risk for torsade de pointes which he fortunately did not have before coming to hospital. The same type ECG...",
      "impression": "Acquired long QT(U) syndrome due to severe hypokalemia (1.5 mEq/L), posing a risk for torsade de pointes.",
      "report": {
        "rhythm": "Normal Sinus Rhythm",
        "rate": "75 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QT(U): ~600 ms, QTc: ~670 ms",
        "findings": "Very prominent U waves, prolonged QT(U) interval, mild ST depression in inferior and lateral leads.",
        "impression": "Acquired long QT(U) syndrome due to severe hypokalemia (1.5 mEq/L), posing a risk for torsade de pointes."
      },
      "topics": [
        "Hypokalemia",
        "Long QT Syndrome"
      ],
      "difficulty": 2,
      "options": [
        "Acquired long QT(U) syndrome due to severe hypokalemia (1.5 mEq/L), posing a risk for torsade de pointes.",
        "Atrial fibrillation (AF) with a slow-moderate ventricular response.",
        "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy.",
        "The patient has hypertrophic obstructive cardiomyopathy (HOCM; formerly IHSS)."
      ],
      "correct_idx": 0
    },
    {
      "case_id": "25",
      "image": "cases/case_25/ekg.gif",
      "clinical_history": "A 38-yr-old woman with weakness. Previous ECG was normal and she was on no medications. What is the most likely diagnosis?",
      "diagnosis": "The ECG shows sinus bradycardia with diffuse T wave flattening or inversions, and markedly prominent U waves. These are best seen in leads V2 and V3, but are essentially invisible in lead aVL. The two most common causes of this finding are 1) Hypokalemia (K+ here was 2.4 mEq/L) and 2) Drugs, especially the class 1A antiarrhythmics (like quinidine, procainamide, disopyramide) and related agents (like the phenothiazines and tricyclics), etc....",
      "impression": "Severe hypokalemia (K+ 2.4 mEq/L) causing characteristic U-waves and repolarization prolongation, placing the patient at high risk for torsade de pointes.",
      "report": {
        "rhythm": "Sinus bradycardia",
        "rate": "46 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QU: 600 ms, QTc: ~530 ms",
        "findings": "Diffuse T-wave flattening and inversions; markedly prominent U-waves, most visible in leads V2 and V3; prolonged ventricular repolarization (QU prolongation).",
        "impression": "Severe hypokalemia (K+ 2.4 mEq/L) causing characteristic U-waves and repolarization prolongation, placing the patient at high risk for torsade de pointes."
      },
      "topics": [
        "Ventricular Tachycardia",
        "Hypokalemia",
        "Long QT Syndrome"
      ],
      "difficulty": 2,
      "options": [
        "Sinus bradycardia and Left Bundle Branch Block (LBBB) with primary ST-T wave changes in the inferior leads, diagnostic of an evolving inferior myocardial infarction (confirmed by positive cardiac biomarkers).",
        "Hypertrophic cardiomyopathy (HCM) with asymmetric septal hypertrophy and significant infranodal conduction system disease.",
        "Severe hypokalemia (K+ 2.4 mEq/L) causing characteristic U-waves and repolarization prolongation, placing the patient at high risk for torsade de pointes.",
        "Coarse atrial fibrillation (not flutter) is present with a slow ventricular response."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "26",
      "image": "cases/case_26/ekg.gif",
      "clinical_history": "This ECG \"speaks\" to some key clues about the underlying major medical condition in this 77-year-old woman.  What does it say? What are the clues and what inference might you make by integrating these findings?",
      "diagnosis": "ECG shows sinus rhythm with left ventricular hypertrophy (LVH), left atrial abnormality and tall peaked T waves best seen in the precordial leads (with non-specific infero-lateral ST depressions). (The QRS duration is slightly prolonged at 110-120 ms,) Also present are left axis deviation consistent with left anterior fascicular block and a long QTc (maximally about 470 ms) Putting it all together, the peaked T waves indicate increased K+ (6.3 mEq/L),...",
      "impression": "Findings strongly suggestive of underlying renal failure based on the triad of hyperkalemia (peaked T-waves), hypocalcemia (prolonged QTc), and chronic hypertension (LVH).",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "63 bpm",
        "axis": "Left axis deviation",
        "intervals": "QRS: 110-120 ms; QTc: ~470 ms",
        "findings": "Left ventricular hypertrophy (LVH), left atrial abnormality, tall peaked T-waves (consistent with hyperkalemia), non-specific infero-lateral ST depressions, prolonged QTc with stretched-out ST segment (consistent with hypocalcemia), left anterior fascicular block (LAFB).",
        "impression": "Findings strongly suggestive of underlying renal failure based on the triad of hyperkalemia (peaked T-waves), hypocalcemia (prolonged QTc), and chronic hypertension (LVH)."
      },
      "topics": [
        "Hyperkalemia",
        "Long QT Syndrome",
        "Left Ventricular Hypertrophy"
      ],
      "difficulty": 4,
      "options": [
        "Findings strongly suggestive of underlying renal failure based on the triad of hyperkalemia (peaked T-waves), hypocalcemia (prolonged QTc), and chronic hypertension (LVH).",
        "Acute inferior/posterior/lateral myocardial infarction (MI) in a man with situs inversus-type dextrocardia.",
        "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy.",
        "Sinus rhythm with atrial bigeminy (this pattern starts after the 4th sinus beat)."
      ],
      "correct_idx": 0
    }
  ],
  "10": [
    {
      "case_id": "10",
      "image": "cases/case_10/ekg.gif",
      "clinical_history": "The patient is an elderly man who presented to the emergency ward with dizziness and new renal failure. What is the cause of the very wide QRS?",
      "diagnosis": "Dx: Hyperkalemia (7.6 mEq/L), secondary to the renal failure. The ECG demonstrates findings consistent with severe hyperkalemia -- most importantly marked widening of the QRS complex. The QRS complex here shows an intraventricular conduction delay (IVCD) with a left bundle branch block (LBBB) morphology and left axis deviation. However, the QRS duration (about 240 ms) is much wider than that seen with an \"uncomplicated\" LBBB (or with left anterior fascicular...",
      "impression": "Severe hyperkalemia (7.6 mEq/L) resulting in profound intraventricular conduction delay and characteristic repolarization changes.",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "65 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: 240 ms, QRS: 240 ms, QTc: 540 ms",
        "findings": "Marked QRS widening (intraventricular conduction delay) with LBBB morphology, peaked T waves, flattened/low-amplitude P waves, and prolonged PR interval (1st degree AV block).",
        "impression": "Severe hyperkalemia (7.6 mEq/L) resulting in profound intraventricular conduction delay and characteristic repolarization changes."
      },
      "topics": [
        "Hyperkalemia",
        "Left Bundle Branch Block"
      ],
      "difficulty": 2,
      "options": [
        "Severe hyperkalemia (7.6 mEq/L) resulting in profound intraventricular conduction delay and characteristic repolarization changes.",
        "c) This tracing is most consistent with AIVR originating from the left ventricle and, therefore, accounts for the atypic",
        "d)  ECG shows a constellation of findings consistent with acute cor pulmonale from massive pulmonary embolus (PE) includ",
        "This is a classic inferior/posterior/right ventricular myocardial infarction (MI) pattern."
      ],
      "correct_idx": 0
    },
    {
      "case_id": "1",
      "image": "cases/case_1/ekg.gif",
      "clinical_history": "21-year-old female with a history of \"seizure\" disorder.  She is on no medications and her electrolytes are normal. This ECG is most consistent with which ONE of the following?",
      "diagnosis": "Dx: Congenital (hereditary) long QT syndrome. The ECG demonstrates sinus rhythm with a very prolonged QT interval of 0.6 second. Note the broad T waves with notching (or possibly U waves) in the precordial leads. This characteristic may identify patients with long QT syndrome at increased risk for torsade de pointes and syncope and sudden death. Patients at high risk of recurrent syncope or sudden death are usually considered for...",
      "impression": "Congenital (hereditary) long QT syndrome",
      "report": {
        "rhythm": "Normal Sinus Rhythm",
        "rate": "52 bpm",
        "axis": "Normal axis",
        "intervals": "PR: 160 ms, QRS: 80 ms, QT: 600 ms, QTc: 557 ms",
        "findings": "Markedly prolonged QT interval (0.6 seconds), broad T waves with prominent notching in precordial leads (V2-V4), sinus bradycardia.",
        "impression": "Congenital (hereditary) long QT syndrome"
      },
      "topics": [
        "Long QT Syndrome"
      ],
      "difficulty": 2,
      "options": [
        "The patient had hypertrophic obstructive cardiomyopathy with chronic left bundle branch block (LBBB).",
        "Congenital (hereditary) long QT syndrome",
        "The left anterior descending (LAD).",
        "Atrial fibrillation with WPW syndrome; medical emergency requiring avoidance of AV nodal blockers and treatment with IV procainamide or DC cardioversion"
      ],
      "correct_idx": 1
    },
    {
      "case_id": "2",
      "image": "cases/case_2/ekg.gif",
      "clinical_history": "18-year-old pre-op ECG for knee surgery. What does this ECG show?",
      "diagnosis": "Limb lead reversal. The left and right arm leads are reversed. The clue is inversion of the P wave and QRS complex in lead I. Whenever you see a negative P wave and QRS complex in lead I the likely diagnosis is limb lead reversal. Dextrocardia is another possibility, but in dextrocardia there is loss of R wave progression in the left chest leads which is not seen in this...",
      "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
      "report": {
        "rhythm": "Sinus arrhythmia",
        "rate": "Approx. 75 bpm (variable due to respiratory sinus arrhythmia)",
        "axis": "Apparent Right Axis Deviation (Lead I negative, aVF positive)",
        "intervals": "PR: ~160 ms, QRS: ~80 ms, QTc: ~450 ms",
        "findings": "Inverted P wave, QRS complex, and T wave in lead I; dissimilarity of QRS morphology between leads I and V6; normal R wave progression in precordial leads; slight J-point and ST-segment elevations consistent with benign early repolarization.",
        "impression": "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia."
      },
      "topics": [
        "Uncategorized"
      ],
      "difficulty": 2,
      "options": [
        "c) This tracing is most consistent with AIVR originating from the left ventricle and, therefore, accounts for the atypic",
        "Limb lead reversal (Left Arm/Right Arm); normal variant early repolarization; respiratory sinus arrhythmia.",
        "Diffuse anterior T wave inversions suggestive of probable ischemia or non-Q wave myocardial infarction (Wellens' syndrome), most likely due to transient proximal LAD occlusion/spasm with subsequent myocardial stunning.",
        "Mitral stenosis with associated left atrial abnormality and right ventricular hypertrophy."
      ],
      "correct_idx": 1
    }
  ],
  "11": [
    {
      "case_id": "17",
      "image": "cases/case_17/ekg.gif",
      "clinical_history": "This 52-year-old man with a history of  \"a cardiac condition\" presents with near syncope. He has no coronary disease. The ECG is most consistent with which ONE of the following diagnoses?",
      "diagnosis": "The ECG reveals sinus rhythm with marked PR prolongation, left ventricular hypertrophy (LVH) by voltage criteria, right bundle branch block (RBBB) with left anterior fascicular block (LAFB), or \"hemiblock\", a prominent initial R in V1, and prominent Q waves laterally. The LVH, and the narrow, morphology of the Q's should suggest the diagnosis of hypertrophic cardiomyopathy (HCM) with asymmetric septal hypertrophy. 93% of patients with HCM have abnormal ECG's. They...",
      "impression": "Hypertrophic cardiomyopathy (HCM) with asymmetric septal hypertrophy and significant infranodal conduction system disease.",
      "report": {
        "rhythm": "Sinus rhythm",
        "rate": "N/A",
        "axis": "Left axis",
        "intervals": "Marked PR prolongation, prolonged QRS (due to RBBB)",
        "findings": "LVH by voltage criteria, Right bundle branch block (RBBB), Left anterior fascicular block (LAFB), prominent initial R in V1, prominent narrow lateral Q waves",
        "impression": "Hypertrophic cardiomyopathy (HCM) with asymmetric septal hypertrophy and significant infranodal conduction system disease."
      },
      "topics": [
        "Right Bundle Branch Block",
        "Wolff-Parkinson-White",
        "Premature Atrial Contractions",
        "Left Ventricular Hypertrophy",
        "Right Ventricular Hypertrophy"
      ],
      "difficulty": 4,
      "options": [
        "e) The ECG shows classic signs of very marked right ventricular hypertrophy (RVH), usually associated with a severe pres",
        "Hypertrophic cardiomyopathy (HCM) with asymmetric septal hypertrophy and significant infranodal conduction system disease.",
        "c)  Flutter waves are well-seen in V1 and lead III (at a  rate of about 280/min, with a ventricular response at about 70",
        "Hypertrophic cardiomyopathy, apical variant (Yamaguchi's syndrome)"
      ],
      "correct_idx": 1
    },
    {
      "case_id": "113",
      "image": "cases/case_113/ekg.gif",
      "clinical_history": "63-year-old female immediately status post cardiac arrest with cardioversion.  What is the likely underlying primary structural abnormality?",
      "diagnosis": "a) Mixed mitral stenosis and regurgitation is most likely. The ECG shows normal sinus rhythm, left atrial abnormality, and voltage criteria for left ventricular hypertrophy (LVH) with borderline right axis deviation. The most likely clinical scenario is mixed mitral stenosis and regurgitation, causing left atrial and biventricular hypertrophy. Hypertensive heart disease alone, or aortic stenosis, would be associated with voltage criteria for LVH on the ECG, but not right axis...",
      "impression": "a) Mixed mitral stenosis and regurgitation is most likely.",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "a) Mixed mitral stenosis and regurgitation is most likely."
      },
      "topics": [
        "Left Ventricular Hypertrophy",
        "Right Ventricular Hypertrophy",
        "Normal Sinus Rhythm"
      ],
      "difficulty": 3,
      "options": [
        "Atrial fibrillation (with a moderate ventricular response) and frequent premature ventricular complexes (PVCs).",
        "Dual chamber pacemaker with AV sequential pacing.",
        "a) The rhythm here is actually sinus at a rate of 94/min with 2:1 AV block and very (!) subtle non-conducted P waves hid",
        "a) Mixed mitral stenosis and regurgitation is most likely."
      ],
      "correct_idx": 3
    },
    {
      "case_id": "178",
      "image": "cases/case_178/ekg.gif",
      "clinical_history": "The following ECG, from an elderly woman, is least consistent with which of the following?",
      "diagnosis": "a). This ECG is least consistent with answer (a). The findings include: atrial fibrillation with an average ventricular rate of about 90/min; an intraventricular conduction delay (IVCD) with left axis deviation (LAD); left ventricular hypertrophy (LVH); and non-specific ST changes. These findings are all consistent with choices b) through e). Severe mitral stenosis, by itself, would NOT be associated with LVH. Abnormalities in severe mitral stenosis typically include atrial fibrillation,...",
      "impression": "a).",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "a)."
      },
      "topics": [
        "Atrial Fibrillation",
        "Left Ventricular Hypertrophy",
        "Right Ventricular Hypertrophy"
      ],
      "difficulty": 3,
      "options": [
        "a).",
        "c) Acute anterior wall ST elevation MI (STEMI).",
        "This is relatively slow bi-directional ventricular tachycardia (VT).",
        "Sinus rhythm is present with very frequent premature atrial complexes (PACs), creating a trigeminal pattern."
      ],
      "correct_idx": 0
    }
  ],
  "12": [
    {
      "case_id": "20",
      "image": "cases/case_20/ekg.gif",
      "clinical_history": "This ECG from a 58-yr-old man shows evidence of WHICH one of the following groups of diagnoses?",
      "diagnosis": "The ECG reveals an acute (likely large) anteroseptal myocardial infarction (MI) in the setting of a (preexisting) right bundle branch block (RBBB). This is a dramatic example of the fact that ischemia and infarction can still be diagnosed, even in the setting of conduction abnormalities. The anterior precordial leads reveal a qR pattern (analagous to an RSR' with the R replaced by a pathologic Q), marked ST elevation, and upright...",
      "impression": "Acute anteroseptal myocardial infarction (MI) in the setting of a preexisting right bundle branch block (RBBB)",
      "report": {
        "rhythm": "N/A",
        "rate": "N/A",
        "axis": "N/A",
        "intervals": "N/A",
        "findings": "Right bundle branch block (RBBB), qR pattern in anterior precordial leads (pathologic Q replacing initial R), marked ST elevation, upright T waves in right precordial leads, pathologic Q waves extending past V2",
        "impression": "Acute anteroseptal myocardial infarction (MI) in the setting of a preexisting right bundle branch block (RBBB)"
      },
      "topics": [
        "Myocardial Infarction",
        "Right Bundle Branch Block"
      ],
      "difficulty": 2,
      "options": [
        "Borderline sinus tachycardia is present with a markedly prolonged PR at about 300 ms (\"1st degree AV block\").",
        "c) Atrial fibrillation with left bundle branch block.~~Note: The coarse atrial fibrillatory waves (lead V1) may be mista",
        "Acute anteroseptal myocardial infarction (MI) in the setting of a preexisting right bundle branch block (RBBB)",
        "Sinus rhythm with atrial bigeminy (this pattern starts after the 4th sinus beat)."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "27",
      "image": "cases/case_27/ekg.gif",
      "clinical_history": "A 52-year-old man.  What is his chief complaint? What is the rhythm disturbance? Look carefully at both ends of strip.",
      "diagnosis": "Acute infero-lateral and probably posterior myocardial infarction (MI) with inferior Q waves and hyperacute ST-T complexes inferiorly and laterally with reciprocal ST depressions V1-V3. Tall initial R waves in V1-V3 with right bundle branch block. There is second degree AV block (Type 1) with 2:1 block initially and then 3:2 AV Wenckebach with underlying sinus rate of about 85/min. Left axis deviation is present. However, since this is an inferior...",
      "impression": "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1).",
      "report": {
        "rhythm": "Sinus rhythm with second-degree AV block (Type 1), featuring initial 2:1 block followed by 3:2 Wenckebach conduction.",
        "rate": "Sinus rate ~85 bpm; Ventricular rate approximately 40-50 bpm.",
        "axis": "Left axis deviation.",
        "intervals": "PR: Variable (prolonging until a dropped beat); QRS: >120 ms (widened, consistent with RBBB); QTc: Not specifically calculated but appears prolonged due to hyperacute T-wave changes.",
        "findings": "Hyperacute ST-segment elevation and T-waves in leads II, III, aVF, and V4-V6; pathologic Q waves in inferior leads (II, III, aVF); reciprocal ST-segment depression in V1-V3; tall initial R waves in V1-V3; Right Bundle Branch Block (RBBB) morphology.",
        "impression": "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1)."
      },
      "topics": [
        "Myocardial Infarction",
        "Right Bundle Branch Block",
        "AV Block",
        "Premature Atrial Contractions"
      ],
      "difficulty": 2,
      "options": [
        "c)  Flutter waves are well-seen in V1 and lead III (at a  rate of about 280/min, with a ventricular response at about 70",
        "e) The ECG shows classic signs of very marked right ventricular hypertrophy (RVH), usually associated with a severe pres",
        "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs).",
        "Acute infero-lateroposterior myocardial infarction complicated by Right Bundle Branch Block (RBBB) and second-degree AV block (Type 1)."
      ],
      "correct_idx": 3
    },
    {
      "case_id": "37",
      "image": "cases/case_37/ekg.gif",
      "clinical_history": "A 67-year-old man. What is the QRS duration?  What is going on?",
      "diagnosis": "The QRS duration is normal. What may appear to be a wide QRS in leads V2-V6 is actually massive ST elevation due to acute transmural anterior ischemia/myocardial infarction (MI) here. There is reciprocal inferior lead ST depression. Q waves are starting to appear in the precordial leads. This ST pattern, called \"tombstones\" in the earthy parlance of the housestaff, is more technically known as a \"monophasic current of injury.\" This...",
      "impression": "Acute transmural anterior myocardial infarction (STEMI) due to left anterior descending (LAD) coronary artery occlusion.",
      "report": {
        "rhythm": "Sinus tachycardia",
        "rate": "110 bpm",
        "axis": "Left axis deviation",
        "intervals": "PR: ~160 ms, QRS: Normal (< 120 ms), QTc: N/A (prolonged due to massive ST segment distortion)",
        "findings": "Massive 'tombstone' ST-segment elevation in leads V2-V6, I, and aVL (monophasic current of injury); Reciprocal ST-segment depression in inferior leads II, III, and aVF; Early Q wave formation in precordial leads.",
        "impression": "Acute transmural anterior myocardial infarction (STEMI) due to left anterior descending (LAD) coronary artery occlusion."
      },
      "topics": [
        "Myocardial Infarction"
      ],
      "difficulty": 2,
      "options": [
        "Acute transmural anterior myocardial infarction (STEMI) due to left anterior descending (LAD) coronary artery occlusion.",
        "Severe hyperkalemia (7.6 mEq/L) resulting in profound intraventricular conduction delay and characteristic repolarization changes.",
        "a)  ECG shows sinus rhythm with the classic Wolff-Parkinson-White (WPW) triad of a short PR; wide QRS; and delta waves.",
        "Marked junctional bradycardia (about 25 beats/min)."
      ],
      "correct_idx": 0
    }
  ],
  "13": [
    {
      "case_id": "228",
      "image": "cases/case_228/ekg.gif",
      "clinical_history": "What is this arrhythmia?",
      "diagnosis": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min). The baseline shows the characteristic wriggly fibrillatory activity (not discrete P waves) and the ventricular response is highly irregular (irregularly irregular). The absence of clearly defined P waves excludes sinus rhythm with premature atrial complexes (PACs) or multifocal atrial tachycardia (MAT.) There are also no consistent flutter (saw-tooth) waves and this...",
      "impression": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min).",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min)."
      },
      "topics": [
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Ventricular Tachycardia",
        "Supraventricular Tachycardia",
        "Premature Atrial Contractions"
      ],
      "difficulty": 2,
      "options": [
        "The rhythm is sinus with underlying left anterior fascicular block (LAFB), and 2:1 conduction in the left posterior fasc",
        "The left anterior descending (LAD).",
        "c) This is a classic example of atrial fibrillation (AF) with a very rapid ventricular response (average about 170/min).",
        "Ventricular tachycardia (VT) at rate of 170."
      ],
      "correct_idx": 2
    },
    {
      "case_id": "323",
      "image": "cases/case_323/ekg.gif",
      "clinical_history": "60 year old woman with palpitations and rapid pulse at rest. The ECG shows which one of the following arrhythmias?",
      "diagnosis": "The ECG shows a very regular narrow complex tachycardia, ventricular rate of 200 bpm. The rate is too fast for resting sinus tachycardia in a patient of this age group. The rhythm is too regular for atrial fibrillation or MAT. The rate is not compatible with atrial flutter with 2:1 conduction since the atrial rate would have to be 400 cycles/min, beyond the atrial depolarization of that rhythm. By exclusion...",
      "impression": "The ECG shows a very regular narrow complex tachycardia, ventricular rate of 200 bpm.",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "The ECG shows a very regular narrow complex tachycardia, ventricular rate of 200 bpm."
      },
      "topics": [
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Ventricular Tachycardia",
        "Supraventricular Tachycardia"
      ],
      "difficulty": 2,
      "options": [
        "The ECG shows a very regular narrow complex tachycardia, ventricular rate of 200 bpm.",
        "This is a classic inferior/posterior/right ventricular myocardial infarction (MI) pattern.",
        "c) The K+ was 10.5 mEq/L in a patient with renal  failure.",
        "a) Electrophysiology study revealed both slow AV nodal conduction (note long PR of conducted beats) and infra-nodal bloc"
      ],
      "correct_idx": 0
    },
    {
      "case_id": "457",
      "image": "cases/case_457/ekg.gif",
      "clinical_history": "Elderly man with palpitations. What is the rhythm?",
      "diagnosis": "The ECG shows atrial fibrillation with a moderate ventricular response (on beta-blocker therapy). Low limb lead voltage, a nonspecific finding, is present. The mean (resting) ventricular rate over 10 seconds is about 70/minute and irregular, without any discernable pattern. Note that the continuous atrial activity (lead V1) is coarse (large amplitude) and nonstationary (variable in appearance and intra-atrial rate), in contrast to atrial flutter where all the atrial waves are...",
      "impression": "The ECG shows atrial fibrillation with a moderate ventricular response (on beta-blocker therapy).",
      "report": {
        "rhythm": "",
        "rate": "",
        "axis": "",
        "intervals": "",
        "findings": "",
        "impression": "The ECG shows atrial fibrillation with a moderate ventricular response (on beta-blocker therapy)."
      },
      "topics": [
        "Atrial Fibrillation",
        "Atrial Flutter",
        "Ventricular Tachycardia",
        "Supraventricular Tachycardia"
      ],
      "difficulty": 2,
      "options": [
        "The ECG shows atrial fibrillation with a moderate ventricular response (on beta-blocker therapy).",
        "The underlying rhythm is sinus at a rate of about 60/min with fixed coupled premature ventricular complexes (PVCs) in a ",
        "Normal sinus rhythm with artifact in V4-V6, simulating premature ventricular complexes (PVCs).",
        "a) Electrophysiology study revealed both slow AV nodal conduction (note long PR of conducted beats) and infra-nodal bloc"
      ],
      "correct_idx": 0
    }
  ]
};
